name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  DEMO_TAG: $(git rev-parse --short HEAD)     

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
        cd cmd/consumer
        GOOS=linux GOARCH=amd64 go build
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_ACCOUNT }}/otel-demo-consumer-go:${{ env.DEMO_TAG }}
        cd ../provider
        GOOS=linux GOARCH=amd64 go build
        docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_ACCOUNT }}/otel-demo-provider-go:${{ env.DEMO_TAG }}
        
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      uses: docker/login-action@v2.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKERHUB_ACCOUNT }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKERHUB_SECRET }}
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKERHUB_ACCOUNT }}/otel-demo-consumer-go:${{ env.DEMO_TAG }}
        docker push ${{ secrets.DOCKERHUB_ACCOUNT }}/otel-demo-provider-go:${{ env.DEMO_TAG }}
